steps:
  # Build da imagem Docker
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/osint-api:latest", "."]

  # Push para Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/osint-api:latest"]

  # Deploy no Cloud Run usando secrets
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "osint-api",
        "--image",
        "gcr.io/$PROJECT_ID/osint-api:latest",
        "--platform",
        "managed",
        "--region",
        "southamerica-east1",
        "--allow-unauthenticated",
        "--update-secrets",
        "SERPAPI_KEY=SERPAPI_KEY:latest,SECRET_AUTH_KEY=SECRET_AUTH_KEY:latest,FACECRAWLER_KEY=FACECRAWLER_KEY:latest,DATABASE_PASSWORD=DATABASE_PASSWORD:latest,DATABASE_PORT=DATABASE_PORT:latest",
      ]
# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/SERPAPI_KEY/versions/latest
#       env: "SERPAPI_KEY"
#     - versionName: projects/$PROJECT_ID/secrets/FACECRAWLER_KEY/versions/latest
#       env: "FACECRAWLER_KEY"
#     - versionName: projects/$PROJECT_ID/secrets/SECRET_AUTH_KEY/versions/latest
#       env: "SECRET_AUTH_KEY"
#     - versionName: projects/$PROJECT_ID/secrets/DATABASE_PASSWORD/versions/latest
#       env: "DATABASE_PASSWORD"
#     - versionName: projects/$PROJECT_ID/secrets/DATABASE_PORT/versions/latest
#       env: "DATABASE_PORT"
